# Generated by Django 6.0.7 on 2026-07-17 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0006_bookmarkedanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='difficulty',
            field=models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='mid', max_length=10),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='question_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='share_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('streak', 'Streak'), ('achievement', 'Achievement'), ('digest', 'Progress Digest'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='resume_api__user_id_0282d8_idx')],
            },
        ),
    ]
