import React from 'react';
import { Box, Container, Typography, Stack } from '@mui/material';
import Header from '../components/layout/Header';
import Footer from '../components/layout/Footer';
import PageHeader from '../components/common/PageHeader';

const Terms: React.FC = () => {
  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
      <Header />
      <Container component="main" maxWidth="md" sx={{ py: 6, flexGrow: 1 }}>
        <PageHeader title="Terms of Service" backTo="/" />
        <Stack spacing={3}>
          <Typography color="text.secondary">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</Typography>

          <Typography>
            CareerCoach AI is a personal/portfolio project provided "as is" to help you tailor resumes,
            practice mock interviews, and prepare for job applications with AI assistance. By creating an
            account and using the app, you agree to the terms below.
          </Typography>

          <Typography variant="h6" fontWeight="bold">1. Your account</Typography>
          <Typography>
            You're responsible for the accuracy of the information you provide and for keeping your
            password secure. You may not share your account with others or use the service for unlawful
            purposes.
          </Typography>

          <Typography variant="h6" fontWeight="bold">2. Content you upload</Typography>
          <Typography>
            Resumes, job descriptions, interview recordings, and chat messages you submit are used solely
            to power the features you invoke (analysis, scoring, chatbot responses) and to show your own
            history back to you. You retain ownership of anything you upload.
          </Typography>

          <Typography variant="h6" fontWeight="bold">3. AI-generated content</Typography>
          <Typography>
            Feedback, scores, and chatbot responses are generated by third-party AI models (including Groq
            and, where configured, Azure Cognitive Services) and may occasionally be inaccurate or
            incomplete. Treat suggestions as a starting point, not professional career or legal advice.
          </Typography>

          <Typography variant="h6" fontWeight="bold">4. No warranty</Typography>
          <Typography>
            The service is provided without warranties of any kind. As a project running on free-tier
            infrastructure, occasional downtime, cold starts, or data resets may occur.
          </Typography>

          <Typography variant="h6" fontWeight="bold">5. Changes</Typography>
          <Typography>
            These terms may be updated as the project evolves. Continued use after a change means you
            accept the updated terms.
          </Typography>

          <Typography variant="h6" fontWeight="bold">6. Contact</Typography>
          <Typography>
            Questions about these terms can be raised via the project's{' '}
            <a href="https://github.com/Gurutej11-web/CareerCoach-AI" target="_blank" rel="noopener noreferrer">
              GitHub repository
            </a>.
          </Typography>
        </Stack>
      </Container>
      <Footer />
    </Box>
  );
};

export default Terms;
