# Generated by Django 6.0.7 on 2026-07-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_created_at_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_target_interviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal_target_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
