# Generated by Django 6.0.7 on 2026-07-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upcoming_interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='upcoming_interview_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
