# Generated by Django 6.0.7 on 2026-07-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_upcoming_interview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry_id', models.PositiveIntegerField(unique=True)),
                ('actor_username', models.CharField(max_length=150)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('content_type_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_repr', models.CharField(max_length=255)),
                ('change_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='career_goal',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='leaderboard_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_achievement_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_progress_digest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_streak_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
